/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AMap: typeof import('./components/MapContainer/view/AMap/index.vue')['default']
    AnimationLayerConfig: typeof import('./components/MapContainer/MapConfig/AnimationLayerConfig.vue')['default']
    AssetslayerConfig: typeof import('./components/MapContainer/MapConfig/AssetslayerConfig.vue')['default']
    BackgroundLayer: typeof import('./components/MapContainer/view/BackgroundLayer.vue')['default']
    Baidu: typeof import('./components/MapContainer/view/Baidu/index.vue')['default']
    BaseConfig: typeof import('./components/MapContainer/MapConfig/BaseConfig.vue')['default']
    BaseDialog: typeof import('./components/Dialog/BaseDialog/index.vue')['default']
    CircleStyleConfigDialog: typeof import('./components/MapContainer/MapStyle/Circle/CircleStyleConfigDialog.vue')['default']
    CircleStyleTable: typeof import('./components/MapContainer/MapStyle/Circle/CircleStyleTable.vue')['default']
    ClusterAssetslayer: typeof import('./components/MapContainer/layer/ClusterAssetslayer.vue')['default']
    ControllerManager: typeof import('./components/MapContainer/controller/ControllerManager.vue')['default']
    Distance: typeof import('./components/MapContainer/controller/Distance.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FullScreen: typeof import('./components/MapContainer/controller/FullScreen.vue')['default']
    GEO_WMTS: typeof import('./components/MapContainer/view/GEO_WMTS/index.vue')['default']
    HeatMap: typeof import('./components/MapContainer/layer/HeatMap.vue')['default']
    HeatMapConfig: typeof import('./components/MapContainer/MapConfig/HeatMapConfig.vue')['default']
    HeatmapControl: typeof import('./components/MapContainer/components/HeatmapControl.vue')['default']
    IconStyleConfigDialog: typeof import('./components/MapContainer/MapStyle/Icon/IconStyleConfigDialog.vue')['default']
    IconStyleTable: typeof import('./components/MapContainer/MapStyle/Icon/IconStyleTable.vue')['default']
    LineStyleConfigDialog: typeof import('./components/MapContainer/MapStyle/Line/LineStyleConfigDialog.vue')['default']
    LineStyleTable: typeof import('./components/MapContainer/MapStyle/Line/LineStyleTable.vue')['default']
    MapContainer: typeof import('./components/MapContainer/index.vue')['default']
    MulitLine: typeof import('./components/MulitLine/index.vue')['default']
    Overlay: typeof import('./components/MapContainer/layer/Overlay.vue')['default']
    OverviewMap: typeof import('./components/MapContainer/controller/OverviewMap.vue')['default']
    PickCoordinate: typeof import('./components/MapContainer/controller/PickCoordinate.vue')['default']
    PolygonStyleConfigDialog: typeof import('./components/MapContainer/MapStyle/Polygon/PolygonStyleConfigDialog.vue')['default']
    PolygonStyleTable: typeof import('./components/MapContainer/MapStyle/Polygon/PolygonStyleTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleLine: typeof import('./components/MapContainer/controller/ScaleLine.vue')['default']
    StaticAssetsLayer: typeof import('./components/MapContainer/layer/StaticAssetsLayer.vue')['default']
    StyleConfig: typeof import('./components/MapContainer/MapConfig/StyleConfig.vue')['default']
    StyleManager: typeof import('./components/MapContainer/MapStyle/StyleManager.vue')['default']
    SwitchCenter: typeof import('./components/MapContainer/controller/SwitchCenter.vue')['default']
    SwitchSource: typeof import('./components/MapContainer/controller/SwitchSource.vue')['default']
    TMS: typeof import('./components/MapContainer/view/TMS/index.vue')['default']
    TMS_GCJ02: typeof import('./components/MapContainer/view/TMS_GCJ02/index.vue')['default']
    WGS_84: typeof import('./components/MapContainer/view/WGS_84/index.vue')['default']
    WorkerClusterAssetslayer: typeof import('./components/MapContainer/layer/WorkerClusterAssetslayer.vue')['default']
    Zoom: typeof import('./components/MapContainer/controller/Zoom.vue')['default']
    ZoomSlider: typeof import('./components/MapContainer/controller/ZoomSlider.vue')['default']
  }
}
